name = "DetailedBalance"
uuid = "d1edd98f-08f7-4164-b17e-431bffdb440b"
authors = ["Harsh Talathi"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
